version: 2

models:
  - name: base_airlines
    description: "This model contains information about different airlines."
    columns:
      - name: airline_id
        data_type: varchar
        description: "Unique identifier for the airline."
        tests:
          - unique
          - not_null

      - name: airline_iata
        data_type: varchar
        description: "IATA code for the airline."
        tests:
          - not_null

      - name: airline_name
        data_type: varchar
        description: "Name of the airline."
        tests:
          - not_null

      - name: _fivetran_synced
        data_type: timestamp_ntz
        description: "Timestamp when the data was last synced by Fivetran."
        tests:
          - not_null

      - name: _fivetran_deleted
        data_type: boolean
        description: "Indicator of whether the data has been deleted."
        tests:
          - not_null

  - name: base_airports
    description: "This model contains information about different airports."
    columns:
      - name: airport_id
        data_type: varchar
        description: "Unique identifier for the airport."
        tests:
          - unique
          - not_null

      - name: airport_name
        data_type: varchar
        description: "Name of the airport."
        tests:
          - not_null

      - name: airport_city
        data_type: varchar
        description: "City where the airport is located."
        tests:
          - not_null

      - name: country_name
        data_type: varchar
        description: "Country where the airport is located."
        tests:
          - not_null

      - name: airport_iata
        data_type: varchar
        description: "IATA code for the airport."
        tests:
          - not_null

      - name: airport_icao
        data_type: varchar
        description: "ICAO code for the airport."
        tests:
          - not_null

      - name: latitude
        data_type: float
        description: "Latitude of the airport's location."
        tests:
          - not_null

      - name: longitude
        data_type: float
        description: "Longitude of the airport's location."
        tests:
          - not_null

      - name: altitude_ft
        data_type: number
        description: "Altitude of the airport in feet."
        tests:
          - not_null

      - name: hours_utc_offset
        data_type: number
        description: "UTC offset of the airport's time zone in hours."

      - name: zona_horaria
        data_type: varchar
        description: "Time zone of the airport."


      - name: tz_timezone
        data_type: varchar
        description: "Time zone of the airport in tz format."

      - name: type
        data_type: varchar
        description: "Type of airport (e.g. international, domestic)."
        tests:
          - not_null

      - name: source
        data_type: varchar
        description: "Source of the airport data."
        tests:
          - not_null

      - name: _fivetran_synced
        data_type: timestamp_ntz
        description: "Timestamp when the data was last synced by Fivetran."
        tests:
          - not_null

      - name: _fivetran_deleted
        data_type: boolean
        description: "Indicator of whether the data has been deleted."
        tests:
          - not_null

  - name: base_countries
    description: "This model contains information about different countries."
    columns:
      - name: country_id
        data_type: varchar
        description: "Unique identifier for the country."
        tests:
          - unique
          - not_null

      - name: country_iata
        data_type: varchar
        description: "IATA code for the country."
        tests:
          - not_null

      - name: country_name
        data_type: varchar
        description: "Name of the country."
        tests:
          - not_null

      - name: _fivetran_synced
        data_type: timestamp_ntz
        description: "Timestamp when the data was last synced by Fivetran."
        tests:
          - not_null

      - name: _fivetran_deleted
        data_type: boolean
        description: "Indicator of whether the data has been deleted."
        tests:
          - not_null

  - name: base_plane_models
    description: "This model contains information about different plane models."
    columns:
      - name: plane_model_id
        data_type: varchar
        description: "Unique identifier for the plane model."
        tests:
          - unique
          - not_null

      - name: code
        data_type: number
        description: "Code for the plane model."
        tests:
          - not_null

      - name: description
        data_type: varchar
        description: "Description of the plane model."
        tests:
          - not_null

      - name: _fivetran_synced
        data_type: timestamp_tz
        description: "Timestamp when the data was last synced by Fivetran."
        tests:
          - not_null

      - name: _fivetran_deleted
        data_type: boolean
        description: "Indicator of whether the data has been deleted."
        tests:
          - not_null


  - name: base_routes
    description: "This table contains information about airline routes, including details about the airlines, airports, aircraft, and passenger volumes."

    columns:
      - name: route_id
        data_type: varchar
        description: "A unique identifier for each route."
        tests:
          - unique
          - not_null

      - name: seats
        data_type: number
        description: "The total number of seats available on the aircraft for the route."

      - name: passengers
        data_type: number
        description: "The number of passengers that flew on the route."

      - name: distance
        data_type: number
        description: "The distance between the origin and destination airports for the route, measured in miles or kilometers."

      - name: airline_iata
        data_type: varchar
        description: "The International Air Transport Association (IATA) code for the airline operating the route."
        tests:
          - not_null

      - name: airline_name
        data_type: varchar
        description: "The name of the airline operating the route."

      - name: origin_airport_iata
        data_type: varchar
        description: "The IATA code for the origin airport of the route."
        tests:
          - not_null

      - name: origin_city_name
        data_type: varchar
        description: "The name of the city where the origin airport is located."

      - name: origin_country_iata
        data_type: varchar
        description: "The IATA code for the country where the origin airport is located."
        tests:
          - not_null

      - name: origin_country_name
        data_type: varchar
        description: "The name of the country where the origin airport is located."

      - name: dest_airport_iata
        data_type: varchar
        description: "The IATA code for the destination airport of the route."
        tests:
          - not_null

      - name: dest_city_name
        data_type: varchar
        description: "The name of the city where the destination airport is located."

      - name: dest_country_iata
        data_type: varchar
        description: "The IATA code for the country where the destination airport is located."

      - name: dest_country_name
        data_type: varchar
        description: "The name of the country where the destination airport is located."

      - name: aircraft_type
        data_type: number
        description: "The type of aircraft used for the route, such as Boeing 737 or Airbus A320."

      - name: year
        data_type: number
        description: "The year in which the data was collected."

      - name: quarter
        data_type: number
        description: "The quarter of the year in which the data was collected, ranging from 1 to 4."

      - name: month
        data_type: number
        description: "The month in which the data was collected, ranging from 1 to 12."

      - name: _fivetran_synced
        data_type: timestamp_tz
        description: "The timestamp indicating when the data was last synced from the source system."

      - name: _fivetran_deleted
        data_type: boolean
        description: "A boolean value indicating whether the data has been deleted from the source system."