version: 2

sources:
  - name: SNOWFLAKE_DB_OPENFLIGHTS
    database: A_VIONCITOS_BRONZE
    tables:
      - name: airlines
      - name: airports
      - name: countries
      - name: plane_models
      - name: routes
      - name: airline_iata